# values.yaml (fragment)
internalCA:
  name: selfsigned-internal-ca
  rootCertName: internal-root-ca
  rootSecretName: internal-root-ca-secret
  commonName: "Internal Root CA"
  issuerName: internal-ca-issuer

certificate:
  enabled: true
  name: default-internal-tls
  namespace: cert-manager
  secretName: default-internal-tls
  commonName: default.internal.lan
  duration: 2160h
  renewBefore: 360h
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "tlta.online"
    - ".cluster.home.tlta.online"