apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rollout-job-aggregator
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: stag01
  chartRef:
    kind: OCIRepository
    name: job-aggregator
    namespace: stag01
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: job-aggregator-values
      valuesKey: values.yaml