minecraft:
  minecraftServer:
    eula: "TRUE"
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 6Gi
      cpu: 4
mc-router:
  services:
    minecraft:
      type: LoadBalancer