{{- if .Values.media.pvcInit.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.media.pvcInit.claimName }}
spec:
  accessModes:
    - {{ .Values.media.pvcInit.accessMode | default "ReadWriteMany" }}
  storageClassName: {{ .Values.media.pvcInit.storageClass | default "longhorn" }}
  resources:
    requests:
      storage: {{ .Values.media.pvcInit.size | default "100Gi" }}
{{- end }}