apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: job-aggregator
  namespace: flux-system
spec:
  interval: 5m
  url: oci://ghcr.io/lynh7/job-aggregator
  ref:
    semver: ">=0.0.0" 