# global:
#   imagePullSecrets:
#     - name: ghcr-creds

database:
  connection:
    enabled: true
    secretName: cnpg-cluster-app
    secretKey: uri

crawlerApi:
  useBrowserImage: true
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
