{{- if .Values.gatewayAPI.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gatewayAPI.name | quote }}
  namespace: {{ .Values.gatewayAPI.namespace | quote }}
  {{- if .Values.gatewayAPI.annotations }}
  annotations:
    {{- toYaml .Values.gatewayAPI.annotations | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: cilium
  listeners:
  {{- range .Values.gatewayAPI.listeners }}
  - name: {{ .name | quote }}
    protocol: {{ .protocol }}
    port: {{ .port }}
    {{- if .hostname }}
    hostname: {{ .hostname | quote }}
    {{- end }}
    {{- if .allowedRoutes }}
    allowedRoutes:
      namespaces:
        from: {{ .allowedRoutes.namespaces.from }}
        {{- if eq .allowedRoutes.namespaces.from "Selector" }}
        selector:
          matchLabels:
            {{- toYaml .allowedRoutes.namespaces.matchLabels | nindent 12 }}
        {{- end }}
    {{- end }}
    {{- if .tls }}
    tls:
      mode: {{ .tls.mode }}
      {{- if .tls.certificateRefs }}
      certificateRefs:
      {{- range .tls.certificateRefs }}
      - name: {{ .name | quote }}
        {{- if .namespace }}
        namespace: {{ .namespace | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}