{{- if .Values.gatewayAPI.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.gatewayAPI.httpRoute.name | quote }}
  namespace: {{ .Values.gatewayAPI.httpRoute.namespace | quote }}
  {{- if .Values.gatewayAPI.httpRoute.annotations }}
  annotations:
    {{- toYaml .Values.gatewayAPI.httpRoute.annotations | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  {{- range .Values.gatewayAPI.httpRoute.parentRefs }}
  - name: {{ .name | quote }}
    kind: {{ .kind | default "Gateway" }}
    namespace: {{ .namespace | default $.Values.gatewayAPI.namespace | quote }}
  {{- end }}
  {{- if .Values.gatewayAPI.httpRoute.hostnames }}
  hostnames:
  {{- range .Values.gatewayAPI.httpRoute.hostnames }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.gatewayAPI.httpRoute.rules }}
  - matches:
    {{- if .matches }}
    {{- range .matches }}
    - path:
        type: {{ .path.type | default "PathPrefix" }}
        value: {{ .path.value | quote }}
    {{- end }}
    {{- end }}
    backendRefs:
    {{- range .backendRefs }}
    - name: {{ .name | quote }}
      port: {{ .port }}
      {{- if .namespace }}
      namespace: {{ .namespace | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}