minecraft:
  minecraftServer:
    eula: "TRUE"
    serviceType: LoadBalancer
    loadBalancerIP: 192.168.100.2
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 6Gi
      cpu: 4
  persistence:
    dataDir:
      # Set this to false if you don't care to persist state between restarts.
      enabled: 10Gi
      Size: 10Gi
      accessModes:
        - ReadWriteOnce
      # existingClaim: nil
      ## specify a subpath in the volume where the data is. Useful when sharing volumes with other apps.
      # subPath: /path/to/dataDir

mc-router:
  services:
    minecraft:
      type: LoadBalancer