vaultwarden:
  dashboard:
    enabled: true
  monitoring:
  # Enable Prometheus ServiceMonitor (requires Prometheus Operator)
  serviceMonitor:
    enabled: true
  env:
    config:
      # Force Node-based Bitwarden CLI to prefer IPv4 DNS results (avoids IPv6 egress timeouts in many clusters)
      NODE_OPTIONS: "--dns-result-order=ipv4first"
      VAULTWARDEN__SERVERURL: "https://vw.tlta.online"
      VAULTWARDEN__ORGANIZATIONID: "" #RECOMMENDED
      VAULTWARDEN__ORGANIZATIONNAME: ""
      VAULTWARDEN__FOLDERID: ""
      VAULTWARDEN__FOLDERNAME: ""
      VAULTWARDEN__COLLECTIONID: "" #RECOMMENDED
      VAULTWARDEN__COLLECTIONNAME: ""
      KUBERNETES__INCLUSTER: "true"
      KUBERNETES__DEFAULTNAMESPACE: "default"
      SYNC__DRYRUN: "false"
      SYNC__DELETEORPHANS: "true"
      SYNC__SECRETPREFIX: ""
      SYNC__SYNCINTERVALSECONDS: "30"
      SYNC__CONTINUOUSSYNC: "true"
      LOGGING__LOGLEVEL__DEFAULT: "Information"
      LOGGING__LOGLEVEL__MICROSOFT: "Warning"
      LOGGING__LOGLEVEL__MICROSOFT__HOSTING__LIFETIME: "Information"