# charts/external-secrets/templates/cluster-secret-store.yaml
{{- if .Values.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: {{ .Values.clusterSecretStore.auth.secretName }}
            key: {{ .Values.clusterSecretStore.auth.clientIdKey }}
            namespace: {{ .Values.clusterSecretStore.auth.namespace }}
          clientSecret:
            name: {{ .Values.clusterSecretStore.auth.secretName }}
            key: {{ .Values.clusterSecretStore.auth.clientSecretKey }}
            namespace: {{ .Values.clusterSecretStore.auth.namespace }}
      secretsScope:
        projectSlug: {{ .Values.clusterSecretStore.infisical.projectSlug | quote }}
        envSlug: {{ .Values.clusterSecretStore.infisical.envSlug | quote }}
{{- end }}