{{- range .Values.clusterSecretStores }}
{{- if .enabled }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: {{ .auth.secretName }}
            key: {{ .auth.clientIdKey }}
            namespace: {{ .auth.namespace }}
          clientSecret:
            name: {{ .auth.secretName }}
            key: {{ .auth.clientSecretKey }}
            namespace: {{ .auth.namespace }}
      secretsScope:
        projectSlug: {{ .infisical.projectSlug | quote }}
        environmentSlug: {{ .infisical.environmentSlug | quote }}
        {{- if .infisical.secretsPath }}
        secretsPath: {{ .infisical.secretsPath | quote }}
        {{- end }}
        {{- if hasKey .infisical "recursive" }}
        recursive: {{ .infisical.recursive }}
        {{- end }}
        {{- if hasKey .infisical "expandSecretReferences" }}
        expandSecretReferences: {{ .infisical.expandSecretReferences }}
        {{- end }}
      {{- if .infisical.hostAPI }}
      hostAPI: {{ .infisical.hostAPI | quote }}
      {{- end }}
      {{- if .infisical.caBundle }}
      caBundle: {{ .infisical.caBundle | quote }}
      {{- end }}
      {{- if .infisical.caProvider }}
      caProvider:
        name: {{ .infisical.caProvider.name | quote }}
        key: {{ .infisical.caProvider.key | quote }}
        type: {{ .infisical.caProvider.type | quote }}
        {{- if .infisical.caProvider.namespace }}
        namespace: {{ .infisical.caProvider.namespace | quote }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}