# charts/external-secrets/templates/external-secrets.yaml
{{- range .Values.externalSecrets }}
{{- if .enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  refreshInterval: {{ .refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $.Values.clusterSecretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .targetSecret }}
    creationPolicy: Owner
    {{- if .targetKind }}
    kind: {{ .targetKind }}
    {{- end }}
    {{- if .template }}
    template:
      {{- if .template.type }}
      type: {{ .template.type }}
      {{- end }}
      {{- if .template.engineVersion }}
      engineVersion: {{ .template.engineVersion }}
      {{- end }}
      {{- if .template.data }}
      data:
        {{- range $key, $val := .template.data }}
        {{ $key }}: |
          {{- $val | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
    {{- end }}
{{- end }}
{{- end }}