# charts/external-secrets/templates/external-secrets.yaml
{{- range .Values.externalSecrets }}
{{- if .enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  refreshInterval: {{ .refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $.Values.clusterSecretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .targetSecret }}
    creationPolicy: Owner
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
    {{- end }}
{{- end }}
{{- end }}