cert-manager:
  crds:
    enabled: true

### cert-manager configuration ###
### WAN configuration ###
issuer:
  name: cloudflare-letsencrypt
  email: hoang.tlta17@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretName: acme-account-key

cloudflare:
  enabled: true
  # apiToken: ""
  apiTokenSecretName: cloudflare-api-token
  apiTokenKey: api-token

### LAN configuration ###
certificate:
  enabled: true
  name: wildcard-cert
  namespace: default
  secretName: wildcard-tls
  dnsNames:
    - "*.cluster.tlta.online"
    - "cluster.tlta.online"