apiVersion: v1
kind: Namespace
metadata:
  name: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    pod-security.kubernetes.io/enforce: {{ .Values.namespaceLabels.podSecurity.enforce | quote }}
    pod-security.kubernetes.io/audit: {{ .Values.namespaceLabels.podSecurity.audit | quote }}
    pod-security.kubernetes.io/warn: {{ .Values.namespaceLabels.podSecurity.warn | quote }}
    {{- if .Values.namespaceLabels.sharedGatewayAccess }}
    shared-gateway-access: {{ .Values.namespaceLabels.sharedGatewayAccess | quote }}
    {{- end }}
