serviceMonitor:
  enabled: true
alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
server:
  name: server
  enabled: true
  
  # vmalert reads metrics from source
  datasource:
    url: "http://victoria-metrics-single-server.monitoring.svc.cluster.local:8428"
  # -- Notifier to use for alerts.
  # Multiple notifiers can be enabled by using `notifiers` section
  notifier:
    alertmanager:
      url: "http://alertmanager.monitoring.svc.cluster.local:8428"