serviceMonitor:
  enabled: true
alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: discord

      group_by:
        - alertname
        - severity
        - namespace

      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h

      routes:
        - matchers:
            - severity="critical"
          receiver: discord

        - matchers:
            - severity="warning"
          receiver: discord

    receivers:
      - name: discord
        discord_configs:
          - webhook_url: ${DISCORD_WEBHOOK}

            send_resolved: true

            title: >-
              {{ if eq .Status "firing" }}🔥{{ else }}✅{{ end }}
              {{ .CommonLabels.alertname }}

            message: |
              **Status:** {{ .Status }}

              **Severity:** {{ .CommonLabels.severity }}

              **Namespace:** {{ .CommonLabels.namespace }}

              **Summary:**
              {{ .CommonAnnotations.summary }}

              **Description:**
              {{ .CommonAnnotations.description }}
  envFrom:
    - secretRef:
        name: discord-webhook
server:
  name: server
  enabled: true
  
  # vmalert reads metrics from source
  datasource:
    url: "http://victoria-metrics-single-server.monitoring.svc.cluster.local:8428"
  # -- Notifier to use for alerts.
  # Multiple notifiers can be enabled by using `notifiers` section
  notifier:
    alertmanager:
      url: "http://alertmanager.monitoring.svc.cluster.local:8428"